### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by fdeberle** [softwerkskammer/Agora-Backlog#115]
Als User der Agora-Plattform möchte ich nach dem Einloggen ein personalisiertes Dashboard sehen.

Dieses Dashboard bietet mir per Widgets einen schnellen Zugriff auf Ressourcen aus meinen Gruppen.

Widgets
------------
1. Meine Gruppen (Unterscheidung: Regional / Themen)
    * Name der Gruppe
    * Art der Gruppe (Regional / Themen)
    * Anzahl Mitglieder (optional)
    * Link zur Gruppenseite
2. Anstehende Termine meiner Gruppen
    * Datum
    * Gruppenname
    * Titel der Activity
    * Ort
    * Link zu der Activity
3. Letzte Änderungen an „meinen“ Wikiseiten (bezogen auf meine Gruppen)
    * Datum der Änderung
    * Titel der Wikiseite (welche Seite wurde bearbeitet?)
    * Name des Bearbeiters
    * Link zu dieser Wikiseite
4. Neueste News
    * Datum des Announcements
    * Titel des Announcements
    * Link zur Announcement-Detailseite

**Comment by leider** [comment]
Ich werde das Dashboard prominent verlinken und dann sehen wir, was die Leute meinen. :)
