### ISSUE TITLE
Benachrichtigungen selektiver gestalten (subscribed groups)

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora-Backlog#134]
Verschiedene Alternativen:
Ich als Mitglied möchte nur Wiki Änderungen erhalten von...
1. Gruppen, in denen ich Mitglied bin.
2. Wikis, für die ich mich explizit interessiere 

Die 2. Alternative erfordert neue Verwaltungsseiten.

**Comment by NicoleRauch** [comment]
In die Agora-Issues übernommen.
