### ISSUE TITLE
Gruppierung in Listenansichten

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora-Backlog#135]
Ich als Benutzer möchte mich in Listen (Aktivitäten, Mitglieder) leichter orientieren können. Dazu stelle ich mir vor, bei Aktivitäten immer eine Zwischenüberschrift für einen Monat und bei Mitgliedern eine pro Anfangsbuchstabe zu sehen

**Comment by NicoleRauch** [comment]
In Agora-Issues übernommen.
