### ISSUE TITLE
Option im Benutzerprofil, die erlaubt eigene Mails vom Mailverteler zurück zu bekommen.

### ISSUE THREAD

**Issue by vinogradoff** [softwerkskammer/Agora-Backlog#146]
Als Erweiterung zu #29  

Eine Checkbox-Option "Versendete Mails vom Verteiler erhalten"  in User Settings (https://www.softwerkskammer.org/members/edit/<Username>) soll eingebaut werden. Ist die Option "ein" so sollen die Emails an alle Verteilermitglieder, einschließlich Versender, verschickt werden.
Ist die Option aus - bleibt es wie jetzt, die Emails werden an alle Verteilermitglieder, ausgenommen Versender, verschickt.

Oder weniger technisch:

Als Benutzer möchte ich eine Option bekommen darüber zu entscheiden, ob meine an Verteiler versendeten Emails auch an mich selbst verschickt werde sollen.

**Comment by leider** [comment]
Wir benutzen ezmlm (https://wiki.uberspace.de/mail:ezmlmidx) - Wenn ich weiß, wie ich das in ezmlm einstellen kann, mach ich das.

**Comment by NicoleRauch** [comment]
Ich mach das dann mal zu hier.

**Comment by NicoleRauch** [comment]
Wenn es noch Bedarf an diesem Feature gibt, bitte in https://github.com/softwerkskammer/Agora wieder aufmachen.
