### ISSUE TITLE
SoCraTes Registrierung

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora-Backlog#147]
### Nach der Freischaltung der Registrierung:
- Umbuchung von Teilnehmern durch Admins:
  - [x] Teilnahmedauer
  - [x] Wahl der Ressource
  - [x] Registrierungsmail versenden bei Umbuchung von der Warteliste
- [x] Pay-Information anzeigen bis zur Bestätigung
- [x] Pay-Information als Button in der Menüleiste
- [x] Avatar-Bilder bearbeitbar machen
- [x] T-Shirt-Ansicht: Summenzeile
- [x] Plätze-Übersicht: Summenzeile
- [x] Mgmt-Screen zum Anzeigen der special requirements der Teilnehmer
- [X] Remove aus Rooms-Zuordnung
- [x] Remove from room booking (auch aus rooms-Zuordnung entfernen)
- [x] Erstellen einer Teilnehmerseite mit den 3 Fragen und Einbauen in die Wiki-Hierarchie
- [x] Beim Remove nicht die participation entfernen!
- [x] Participants mit DZ-Belegung sehen ihren zugeteilten Partner auf ihrem Member-Profil
- [x] Participants mit DZ-Belegung ohne zugeteilten Partner sehen die möglichen Partner in ihrem Member-Profil
- [x] SoCraTes-Wiki-Mailings mit Opt-Out
- [x] Remove from waitinglist (participation nicht entfernen!)
- [x] Anzeigen der Nicht-Teilnehmer, die bezahlt haben
- [x] Session Snap einbauen
- [x] Generieren eines Geldrückgabe-Unterschrifts-Zettels für die SoCraTes (mit T-Shirt-Größe)
- [x] LaTeX-Dokument zum Drucken der Namensschilder generieren
- [x] Umstellen der SoCraTes-Admin-Berechtigungen auf die Middleware (Tests!)
- [x] Anzeigen der SoCraTes-Teilnahmen auf den Seiten der Subscriber in der SoCraTes.
- [x] Fehler beim Bezahlen sollten deutlicher erkennbar sein
- [x] Nachdem ein Teilnehmer per Überweisung bezahlt hat, sollte er trotzdem noch per Kreditkarte bezahlen können.
- [x] Beim Verschieben eines Benutzers mit Room-Zuordnung die Zuordnung entfernen
- [x] Übersicht: Wie viel Geld eingegangen ist
- [x] Softwerkskammer-Mitglieder beim Löschen nur dann entfernen, wenn sie nicht in der SoCraTes sind - ansonsten nur als socrates-only markieren...
- [x] Wartelisten-Tests (unit und integration)
- [x] Alle Tests überprüfen und ggf. ergänzen
- [x] Bug: Wartelisten-Adressen zeigen die gewählte Ressource nicht an
- [x] Management-Seiten öffnen sich auf dem gleichen Tab wie vorher
- [x] Test: Submit schlägt fehl, wenn das Jahr verändert wird
- [x] /qrcode kann auch aus der SWK geholt werden
- [x] Anzeigen der freien / belegten / blockierten Plätze??
### Nach der SoCraTes:
- [x] New-Button in die Buttonleiste aufnehmen
- [x] Activities in Softwerkskammer und SoCraTes trennen, beide simplifizieren
- [x] WaitinglistEntry und RegistrationEntry gleich machen zum einfacheren Herumschieben
- [x] Meldet sich jemand während der Registrierung an, bekommt der Admin 2 Mails. Besser nur eine?
- [x] Wartelisten-Mail: "waitinglist data" ist missverständlich. Bessere Formulierung finden.
- [x] Die Jahreszahl muss überall aus der Variablen in socratesConstants genommen werden: registration/get, notification-Templates, ...
- [x] Feld "Land" zum schnelleren Erfassen der Zahl der Ausländer (auch in SWK)
- [x] Eine einzige Warteliste, wo die Leute ankreuzen können, wo sie hingehen würden.
### Gar nicht:
- [ ] Löschen einer Activity unter /activities/delete/...

**Comment by c089** [comment]
#protip: you can do todo lists in github flavoured markdown:

* [ ] a
* [ ] b

**Comment by NicoleRauch** [comment]
@c089 Oh nice, thank you!

**Comment by leider** [comment]
Kannst Du den nochmal durchsehen?
