### ISSUE TITLE
Interaktion zwischen Landkarte und Kalenderwidget

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora-Backlog#60]
Fahre ich auf der Landkarte über eine Regionalgruppe, sollen in den angezeigten Kalendern die Events dieser Gruppe hervorgehoben werden.

Fahre ich in einem Kalender über ein Event, soll die Regionalgruppe auf der Landkarte hervorgehoben werden.

**Comment by leider** [comment]
Ich sehe den Nutzen nicht - im Vergleich zum Aufwand. Darüberhinaus muss dazu die Landing Page mit Karte offen sein.

Das Schließen überlasse ich Dir.
